name: TechMarket Orders - Examen Transversal

on:
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" 

jobs:
  
  run-build-template:
    name: Ejecutar Plantilla de Construcción
    uses: ./.github/workflows/build-template.yml
    with:
      image_tag: "et-2026-release"

  
  run-deploy-and-remediation:
    name: Ejecutar Plantilla de Despliegue y Caos
    needs: run-build-template
    uses: ./.github/workflows/deploy-template.yml
    with:
      target_env: "green"
    secrets: inherit 
